version: '3.5'

services:

  mongo:
    image: mongo:3.4.18
    container_name: indyscan-mongo
    networks:
    - indynet
    volumes:
    -  indyscandb:/data/db
    ports:
    - 27999:27017

  indyscan-daemon:
    image: indyscan-daemon:latest
    container_name: indyscan-daemon
    volumes:
      - ${HOME}/.indy_client/pool:/home/indyscan/.indy_client/pool
    network_mode: host
    depends_on:
    - mongo
    environment:
    - URL_MONGO=mongodb://localhost:27999
    - INDY_NETWORKS=${INDY_NETWORKS}
    - SCAN_MODE=${SCAN_MODE}

volumes:
  indyscandb:
    external: false

networks:
  indynet:
    name: indynet
    driver: bridge
