version: '3.5'

services:

  indyscan:
    image: ${WEBAPP_IMAGE}
    container_name: indyscan-webapp
    networks:
      - indynet
    environment:
      - URL_MONGO=${URL_MONGO}
      - INDY_NETWORKS=${INDY_NETWORKS}
      - WEBAPP_PORT=5050
    ports:
      - '5050:5050'

volumes:
  indyscandb:
    external: false

networks:
  indynet:
    name: indynet
    driver: bridge
